# This .yml file is used to specify the conda environment that should be loaded into the RTD instance
name: teqpdocs
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - doxygen
  - cmake
  - pandoc
  - jupyter
  - notebook
  - nbconvert
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pip:
    - breathe
    - teqp
    - nbsphinx
    - PCSAFTsuperanc
    - sphinxcontrib-doxylink
    - insipid-sphinx-theme
    - CoolProp
