name: build and run Catch tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: mkdir
      run: mkdir build && cd build
    - name: cmake config
      run: cd build && CXX=clang++ cmake .. -DCMAKE_BUILD_TYPE=Release -DTEQP_SNIPPETS=ON
    - name: build Catch tests
      run: cmake --build build --target catch_tests
    - name: run Catch tests
      run: cd build && ctest --verbose
    - name: build multifluid
      run: cmake --build build --target multifluid
    - name: build teqp Python package
      run: CXX=clang++ python setup.py build
